#!/usr/bin/env sh

echo "⏳ Running lint-staged config..."
npx lint-staged
echo "✅ Lint-staged config passed"
echo "--------------------------------"

echo "⏳ Running lint..."
npm run lint
echo "✅ Lint passed"
echo "--------------------------------"

echo ✅ All pre-commit jobs are done